spring:
  application:
    name: eureka

server:
  port: 8761

management:
  server:
    port: 8762
  info:
    os:
      enabled: true
    java:
      enabled: true
    process:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  file:
    path: build/log